// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package solid16

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ComputerDesktopIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" class=\"w-4 h-4\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M2 4.25C2 3.00736 3.00736 2 4.25 2H11.75C12.9926 2 14 3.00736 14 4.25V9.75C14 10.9926 12.9926 12 11.75 12H10.438C10.5382 12.128 10.6477 12.2485 10.7657 12.3602C10.9153 12.5018 11 12.6988 11 12.9048V13.25C11 13.6642 10.6642 14 10.25 14H5.75C5.33579 14 5 13.6642 5 13.25V12.9048C5 12.6988 5.08472 12.5018 5.23428 12.3602C5.35228 12.2485 5.46184 12.128 5.56197 12H4.25C3.00736 12 2 10.9926 2 9.75V4.25ZM4.25 3.5C3.83579 3.5 3.5 3.83579 3.5 4.25V8.75C3.5 9.16421 3.83579 9.5 4.25 9.5H11.75C12.1642 9.5 12.5 9.16421 12.5 8.75V4.25C12.5 3.83579 12.1642 3.5 11.75 3.5H4.25Z\" fill=\"black\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
