// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package solid16

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func HeartIcon(attrs templ.Attributes) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" viewBox=\"0 0 16 16\" class=\"w-4 h-4\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("><path d=\"M2.00019 6.34163C2.01809 4.49304 3.5222 3 5.37503 3C6.43525 3 7.38129 3.48888 8.00003 4.2535C8.61876 3.48888 9.5648 3 10.625 3C12.489 3 14 4.51104 14 6.375C14 6.42155 13.9991 6.46792 13.9972 6.51409C13.9335 8.64751 12.3785 10.2732 11.0417 11.298C10.3524 11.8264 9.67051 12.234 9.16292 12.5091C8.90827 12.6471 8.6953 12.7529 8.54433 12.825C8.46878 12.861 8.40861 12.8887 8.36632 12.9078C8.34517 12.9173 8.32848 12.9247 8.31657 12.93L8.3023 12.9362L8.29793 12.9381L8.29644 12.9387C8.11018 13.02 7.89018 13.02 7.70423 12.939L7.70215 12.9381L7.6977 12.9362L7.68318 12.9298C7.67105 12.9245 7.65405 12.9169 7.6325 12.9072C7.58941 12.8878 7.5281 12.8596 7.45115 12.8228C7.29738 12.7494 7.08053 12.6415 6.82155 12.5008C6.30539 12.2203 5.61283 11.8047 4.91593 11.2659C3.56388 10.2205 1.99929 8.55828 1.99921 6.38003C1.99921 6.36719 1.99953 6.35439 2.00019 6.34163Z\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
