// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package solid16

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func MusicalNoteIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M13.9997 1.75001C13.9997 1.52652 13.9 1.31467 13.7278 1.17219C13.5557 1.02971 13.3289 0.971435 13.1094 1.01325L5.60771 2.44214C5.25397 2.50952 4.99805 2.81879 4.99805 3.17889V5.67889C4.99805 5.69702 4.9987 5.71507 5 5.73302V9.73045C5 10.2106 4.65876 10.6229 4.18711 10.7128L3.60783 10.8231C2.67494 11.0008 2 11.8165 2 12.7661C2 14.0069 3.12916 14.9413 4.34802 14.7091L4.9509 14.5943C5.85043 14.4229 6.50123 13.6365 6.50123 12.7208V11.1783C6.50123 11.164 6.50082 11.1496 6.5 11.1354V6.29915L12.5 5.15629V8.30188C12.5 8.78201 12.1588 9.19438 11.6871 9.28421L11.103 9.39547C10.1701 9.57317 9.49518 10.3888 9.49518 11.3385C9.49518 12.5792 10.6243 13.5136 11.8432 13.2815L12.169 13.2194C13.2314 13.017 14 12.0882 14 11.0068L13.9997 1.75001Z\" fill=\"black\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
