// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package solid16

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ShieldCheckIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" class=\"w-4 h-4\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M8.50019 1.70873C8.21543 1.45386 7.78457 1.45386 7.49981 1.70873C6.1781 2.89169 4.50633 3.6889 2.65985 3.92627C2.29508 3.97316 2.01813 4.27764 2.0059 4.64521C2.00198 4.7631 2 4.88145 2 5.00023C2 9.05223 4.29542 12.5669 7.65336 14.317C7.87059 14.4302 8.12941 14.4302 8.34664 14.317C11.7046 12.5669 14 9.05223 14 5.00023C14 4.88145 13.998 4.7631 13.9941 4.64522C13.9819 4.27764 13.7049 3.97316 13.3401 3.92627C11.4937 3.6889 9.8219 2.89169 8.50019 1.70873ZM10.8398 7.21337C11.0957 6.88766 11.0391 6.41617 10.7134 6.16026C10.3877 5.90435 9.91618 5.96093 9.66027 6.28664L7.39384 9.17119L6.23811 8.18056C5.92361 7.91099 5.45014 7.94741 5.18057 8.26191C4.911 8.5764 4.94743 9.04988 5.26192 9.31944L7.01192 10.8194C7.16716 10.9525 7.36999 11.0164 7.57347 10.9964C7.77695 10.9764 7.96343 10.8741 8.08975 10.7134L10.8398 7.21337Z\" fill=\"black\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
