// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package solid20

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SpeakerWaveIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" class=\"w-5 h-5\"><path d=\"M10.5 3.75002C10.5 3.4508 10.3221 3.18021 10.0475 3.06153C9.7728 2.94286 9.45387 2.99879 9.23598 3.20387L5.20257 7.00002H2.66724C2.35725 7.00002 2.0792 7.19074 1.96756 7.47993C1.66534 8.26287 1.5 9.11302 1.5 10C1.5 10.887 1.66534 11.7372 1.96756 12.5201C2.0792 12.8093 2.35725 13 2.66724 13H5.20257L9.23598 16.7962C9.45387 17.0012 9.7728 17.0572 10.0475 16.9385C10.3221 16.8198 10.5 16.5492 10.5 16.25V3.75002Z\" fill=\"#0F172A\"></path> <path d=\"M16.4498 5.05029C16.1569 4.7574 15.682 4.7574 15.3891 5.05029C15.0962 5.34318 15.0962 5.81806 15.3891 6.11095C17.537 8.25883 17.537 11.7412 15.3891 13.8891C15.0962 14.182 15.0962 14.6569 15.3891 14.9498C15.682 15.2427 16.1569 15.2427 16.4498 14.9498C19.1834 12.2161 19.1834 7.78396 16.4498 5.05029Z\" fill=\"#0F172A\"></path> <path d=\"M14.3287 7.1716C14.0358 6.8787 13.5609 6.8787 13.268 7.1716C12.9751 7.46449 12.9751 7.93936 13.268 8.23226C14.2443 9.20857 14.2443 10.7915 13.268 11.7678C12.9751 12.0607 12.9751 12.5356 13.268 12.8285C13.5609 13.1213 14.0358 13.1213 14.3287 12.8285C15.8908 11.2664 15.8908 8.73369 14.3287 7.1716Z\" fill=\"#0F172A\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
